USE ROLE USERADMIN;

-- Create user roles

CREATE ROLE DLT COMMENT = 'Able to operate data in staging layer of warehouse';
CREATE ROLE DBT COMMENT = 'Able to operate in warehouse and mart layer of warehouse';
CREATE ROLE ANALYZING COMMENT = 'Able to operate in mart layer of warehouse';

-- User roles

USE ROLE SECURITYADMIN;

-- DLT

GRANT USAGE ON ALL SCHEMAS IN DATABASE group4_db TO ROLE DLT;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA group4_db.staging TO ROLE DLT;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA group4_db.staging TO ROLE DLT;
GRANT CREATE TABLE ON SCHEMA group4_db.staging TO ROLE DLT;

GRANT USAGE ON DATABASE group4_db TO ROLE DLT;
GRANT USAGE ON SCHEMA group4_db.staging   TO ROLE DLT;
GRANT USAGE ON SCHEMA group4_db.warehouse TO ROLE DLT;
GRANT USAGE ON SCHEMA group4_db.mart      TO ROLE DLT;

GRANT USAGE   ON WAREHOUSE group4_wh TO ROLE DLT;
GRANT OPERATE ON WAREHOUSE group4_wh TO ROLE DLT; 

SHOW GRANTS TO ROLE DLT;

-- DBT 

USE ROLE SECURITYADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE group4_db TO ROLE DBT;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA group4_db.staging TO ROLE DBT;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA group4_db.staging TO ROLE DBT;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA group4_db.WAREHOUSE TO ROLE DBT;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA group4_db.WAREHOUSE TO ROLE DBT;

GRANT CREATE TABLE ON SCHEMA group4_db.staging TO ROLE DBT;
GRANT CREATE TABLE ON SCHEMA group4_db.warehouse TO ROLE DBT;
GRANT CREATE TABLE ON SCHEMA group4_db.warehouse TO ROLE DBT;


GRANT USAGE ON DATABASE group4_db TO ROLE DBT;
GRANT USAGE ON SCHEMA group4_db.staging   TO ROLE DBT;
GRANT USAGE ON SCHEMA group4_db.warehouse TO ROLE DBT;
GRANT USAGE ON SCHEMA group4_db.mart      TO ROLE DBT;

GRANT USAGE   ON WAREHOUSE group4_wh TO ROLE DBT;
GRANT OPERATE ON WAREHOUSE group4_wh TO ROLE DBT;
SHOW GRANTS TO ROLE DBT;

-- ANALYZING

USE ROLE SECURITYADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE group4_db TO ROLE ANALYZING;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA group4_db.mart TO ROLE ANALYZING;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA group4_db.mart TO ROLE ANALYZING;

GRANT CREATE TABLE ON SCHEMA group4_db.mart TO ROLE analyzing;

GRANT USAGE ON DATABASE group4_db TO ROLE ANALYZING;
GRANT USAGE ON SCHEMA group4_db.staging   TO ROLE ANALYZING;
GRANT USAGE ON SCHEMA group4_db.warehouse TO ROLE ANALYZING;
GRANT USAGE ON SCHEMA group4_db.mart      TO ROLE ANALYZING;

GRANT USAGE   ON WAREHOUSE group4_wh TO ROLE ANALYZING;
GRANT OPERATE ON WAREHOUSE group4_wh TO ROLE ANALYZING;

SHOW GRANTS TO ROLE ANALYZING;

-- Granting users access to roles

SHOW USERS;

SHOW GRANTS TO USER ALEXANDERHRACHOVINA;
SHOW GRANTS TO USER EYOUBBERAKI;

GRANT ROLE ACCOUNTADMIN TO USER ALEXANDERHRACHOVINA;
GRANT ROLE ACCOUNTADMIN TO USER EYOUBBERAKI;
GRANT ROLE ACCOUNTADMIN TO USER ERIKUNEVIK;


USE ROLE SECURITYADMIN;

GRANT ROLE DLT, DBT, ANALYZING TO USER ERIKUNEVIK;
GRANT ROLE DLT, DBT, ANALYZING TO USER ALEXANDERHRACHOVINA;
GRANT ROLE DLT, DBT, ANALYZING TO USER EYOUBBERAKI;

SHOW GRANTS TO USER ERIKUNEVIK;
SHOW GRANTS TO USER ALEXANDERHRACHOVINA;
SHOW GRANTS TO USER EYOUBBERAKI;











