# Testa att det inte finns n책gra null v채rden i ID variablerna i fct_jobs_ads och att den
# referentiella intergriteten st채mmer med dim modellernas ID, dvs de pekar p책 varandra. 

models:
  - name: fct_job_ads
    columns:
      - name: job_details_id
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_job_details')
              field: job_details_id

      - name: employer_id
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_employer')
              field: employer_id

      - name: occupation_id
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_occupation')
              field: occupation_id

      - name: auxilliary_attributes_id
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_auxilliary_attributes')
              field: auxilliary_attributes_id


            



                

        